/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_815551_95_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_815551_17[] = { "earthquake_local", "noise" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_815551_94_axes[] = { 0 };
const uint32_t ei_dsp_config_815551_94_axes_size = 1;
ei_dsp_config_spectral_analysis_t ei_dsp_config_815551_94 = {
    94, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    0.00000001200584f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "Wavelet", // select analysis-type
    4096, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    3, // int wavelet-level
    "bior3.7", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_815551_94[56] = { 3.2735072139104537, 0.40475008861993617, 0.4479637065978409, -0.002055267757394674, -0.000534700001957804, 0.0005229175848595695, 0.00209027262785485, 0.0000013273803475172211, -0.0000014236173540722478, 0.001361796940808691, 0.00013427562124624417, 0.0013633089104268486, 0.0086610377362699, 3.3717445525449654, 3.041850381054428, 0.31386783850104055, 0.36270767482501437, -0.000777801626628249, -0.0001559923210222878, 0.00015818288275829616, 0.0007822876088234983, 0.000001445592902610735, 4.250134032604676e-8, 0.0005396103855498861, 0.00003089350458679939, 0.0005418355272147931, -0.005515951508731255, 5.027222776510986, 2.891312854407399, 0.3481492246563725, 0.40680723704977845, -0.00022817798431451727, -0.000040997953131639566, 0.00004065343115812917, 0.0002293676126572569, -1.3318915484835865e-7, -7.638114844696143e-8, 0.00015285300876574908, 0.0000026269627211998157, 0.00015307433040045713, 0.0028342369073106896, 9.239080719260977, 2.2717337519715226, 0.29820440302693885, 0.3715823646083181, -0.000034570633759237306, -0.000005857183401586543, 0.0000059127056438912536, 0.000034359126103257625, 3.4081116941817e-9, 1.0047976297596566e-12, 0.00002366467486187462, 6.414552458099196e-8, 0.000023664728225512484, 0.0032699599487550505, 11.898504040794844 };
const float ei_dn_standard_scaler_scale_815551_94[56] = { 0.9136664805776182, 4.421453108882977, 4.737286929831859, 57.17121780729373, 234.8076124337025, 253.0076188669572, 54.97216096351889, 2350.7324006029335, 1881.8181054218062, 87.22135120154829, 195.31395281436602, 87.12917739040141, 0.8251610418249639, 0.0758346913432614, 0.7978267225244109, 5.041366717216338, 5.726717076908515, 135.16572970119321, 752.4487034334651, 692.9141931979769, 132.9670052379439, 8657.934902553796, 2512.222464136145, 181.4333540379926, 669.9486800428699, 180.96916721457958, 0.6694353389129604, 0.0640974661403733, 0.7244484605327293, 4.083568951531194, 4.442582825986478, 395.1800324061041, 2614.678530011994, 2686.577978600454, 357.18647353334455, 55637.58499571933, 12820.972725731333, 620.9463161001677, 7774.4761945063665, 620.2274077120645, 0.5088573710137055, 0.03224853292054207, 0.6185319450032343, 3.754784476020276, 3.6455169386666557, 2695.429432198419, 18219.95513805545, 18035.675737078134, 2732.674870463791, 733359.9846807093, 2799164.094018341, 3969.661091037661, 362005.3246194652, 3969.6571730289247, 0.43487788144223977, 0.019563614093723654 };
const float ei_dn_standard_scaler_var_815551_94[56] = { 1.1979111720093958, 0.05115286382194633, 0.04455953190124559, 0.0003059462352897086, 0.000018137426054339767, 0.000015621862152559443, 0.0003309134207356225, 1.809645942258829e-7, 2.8238700978902816e-7, 0.0001314481200739469, 0.000026214010017464458, 0.0001317263846770502, 1.468664403831495, 173.88581413530414, 1.57102408414103, 0.03934625663047366, 0.03049218489545196, 0.0000547352131130639, 0.0000017662257155332717, 0.0000020827689067120556, 0.00005656036782909978, 1.334047728754806e-8, 1.584469233029608e-7, 0.00003037845913565102, 0.0000022280089362997483, 0.00003053450080386764, 2.231427241487203, 243.3987125885102, 1.90539496055751, 0.05996808960537773, 0.050667436656425036, 0.0000064033909074591364, 1.4627274058584924e-7, 1.3854826729829583e-7, 0.000007838085416729467, 3.2304532354241263e-10, 6.083563525603842e-9, 0.0000025935336684367293, 1.6544655321273535e-8, 0.0000025995495060751522, 3.861960791740075, 961.5681633367559, 2.6138203288383233, 0.07093000210630418, 0.07524571252221736, 1.376398109696046e-7, 3.0123497432005458e-9, 3.074221552301687e-9, 1.3391341145597792e-7, 1.8593689806248247e-12, 1.276272121405865e-13, 6.345898754886707e-8, 7.630800211088957e-12, 6.345911281559893e-8, 5.287682394788273, 2612.7738758794226 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_815551_94 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_815551_94,
    .mean_data_len = 56,
    .scale_data = (float *)ei_dn_standard_scaler_scale_815551_94,
    .scale_data_len = 56,
    .var_data = (float *)ei_dn_standard_scaler_var_815551_94,
    .var_data_len = 56
};
ei_data_normalization_t ei_data_normalization_config_815551_94 = {
    (void *) &ei_data_normalization_standard_scaler_config_815551_94, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_815551_17_size = 1;
ei_model_dsp_t ei_dsp_blocks_815551_17[ei_dsp_blocks_815551_17_size] = {
    { // DSP block 94
        94,
        56, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_815551_94, // pointer to config struct
        ei_dsp_config_815551_94_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_815551_94_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_815551_94, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_815551_95 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_815551_95_init,
    .model_invoke = &tflite_learn_815551_95_invoke,
    .model_reset = &tflite_learn_815551_95_reset,
    .model_input = &tflite_learn_815551_95_input,
    .model_output = &tflite_learn_815551_95_output,
};

const uint8_t ei_output_tensors_indices_815551_95[1] = { 0 };
const uint8_t ei_output_tensors_size_815551_95 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_815551_95 = {
    .implementation_version = 1,
    .block_id = 95,
    .output_tensors_indices = ei_output_tensors_indices_815551_95,
    .output_tensors_size = ei_output_tensors_size_815551_95,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_815551_95,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_815551_17_size = 1;
const uint32_t ei_learning_block_815551_95_inputs[1] = { 94 };
const uint8_t ei_learning_block_815551_95_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_815551_17[ei_learning_blocks_815551_17_size] = {
    {
        95,
        &run_nn_inference,
        (void*)&ei_learning_block_config_815551_95,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_815551_95_inputs,
        ei_learning_block_815551_95_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_815551_17_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_815551_17[ei_postprocessing_blocks_815551_17_size] = {
    {
        .block_id = 95,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 95
    },
};

const uint8_t freeform_outputs_815551_17_size = 0;

uint32_t *freeform_outputs_815551_17 = nullptr;

const ei_impulse_t impulse_815551_17 = {
    .project_id = 815551,
    .project_owner = "Nithin  Aravindan",
    .project_name = "SEISMIC_PROJECT",
    .impulse_id = 17,
    .impulse_name = "Impulse #16",
    .deploy_version = 10,

    .nn_input_frame_size = 56,
    .raw_sample_count = 1000,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 1000 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 10,
    .frequency = 100,

    .dsp_blocks_size = ei_dsp_blocks_815551_17_size,
    .dsp_blocks = ei_dsp_blocks_815551_17,

    .learning_blocks_size = ei_learning_blocks_815551_17_size,
    .learning_blocks = ei_learning_blocks_815551_17,

    .postprocessing_blocks_size = ei_postprocessing_blocks_815551_17_size,
    .postprocessing_blocks = ei_postprocessing_blocks_815551_17,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "Z_channel",
    .slice_size = (1000/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_815551_17,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_815551_17_size,
    .freeform_outputs = freeform_outputs_815551_17
};

ei_impulse_handle_t impulse_handle_815551_17 = ei_impulse_handle_t( &impulse_815551_17 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_815551_17;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_815551_17;
const auto ei_dsp_blocks_size = ei_dsp_blocks_815551_17_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_815551_17;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
